/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Agentes.Agent_Master;
import LogicaJuego.Ficha;
import LogicaJuego.Juego;

/**
 *
 * @author Ander
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    
    
    Agent_Master creador;
    Object [] argumentos;
    
    
    public Menu() {
        initComponents();
        creador = new Agent_Master();
        creador.initController();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Hvsa = new javax.swing.JButton();
        Avsa = new javax.swing.JButton();
        Hvsh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Molino");
        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Seleccionar Modo de Juego");

        Hvsa.setBackground(new java.awt.Color(102, 0, 255));
        Hvsa.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Hvsa.setText("Humano vs Agente");
        Hvsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HvsaActionPerformed(evt);
            }
        });

        Avsa.setBackground(new java.awt.Color(102, 0, 255));
        Avsa.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Avsa.setText("Agente vs Agente");
        Avsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvsaActionPerformed(evt);
            }
        });

        Hvsh.setBackground(new java.awt.Color(102, 0, 255));
        Hvsh.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        Hvsh.setText("Humano vs Humano");
        Hvsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HvshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hvsh, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Avsa, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Hvsa, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(Hvsa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Avsa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Hvsh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HvsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HvsaActionPerformed
        argumentos= new Object[4];
        argumentos[0]=Ficha.JUGADOR_2;
        argumentos[1]=Juego.NUMERO_FICHAS_POR_JUGADOR;
        argumentos[2]=4;
        argumentos[3]=false;
        creador.initAgent("Player_1", "Agentes.Agent_Player", null);
        creador.initAgent("Player_2", "Agentes.Agent_Minimax", argumentos);
        this.setVisible(false);
    }//GEN-LAST:event_HvsaActionPerformed

    private void AvsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvsaActionPerformed
        argumentos= new Object[4];
        argumentos[0]=Ficha.JUGADOR_1;
        argumentos[1]=Juego.NUMERO_FICHAS_POR_JUGADOR;
        argumentos[2]=4;
        argumentos[3]=true;
        creador.initAgent("Player_1", "Agentes.Agent_Minimax", argumentos);
        Object args [] = new Object[4];
        args[0]=Ficha.JUGADOR_2;
        args[1]=Juego.NUMERO_FICHAS_POR_JUGADOR;
        args[2]=4;
        args[3]=false;
        creador.initAgent("Player_2", "Agentes.Agent_Minimax", args);
       // creador.initAgent("manager", "Agentes.Agent_Manager", null);
        this.setVisible(false);
    }//GEN-LAST:event_AvsaActionPerformed

    private void HvshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HvshActionPerformed
        creador.initAgent("Player_1", "Agentes.Agent_Player", null);
        creador.initAgent("Player_2", "Agentes.Agent_Player", null);
        this.setVisible(false);
    }//GEN-LAST:event_HvshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avsa;
    private javax.swing.JButton Hvsa;
    private javax.swing.JButton Hvsh;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
