/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Agentes.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import sun.management.Agent;
import LogicaJuego.*;
import jade.gui.GuiEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ander
 */
public class PhysicalBoard extends javax.swing.JFrame {

    /**
     * Creates new form PhysicalBoard
     */
    Panel panel;
    Agent_Manager Manager;
    Panel[] boardPositions;

    public PhysicalBoard() {
        initComponents();
        IniciarTablero();
        setSize(500, 500);
        

    }

    public void repintar() {
        panel.repaint();
        for (int i = 0; i < boardPositions.length && boardPositions[i] != null; i++) {
            boardPositions[i].repaint();
        }
    }

    public void ActualizarTablero() throws JuegoException {
        for (int i = 0; i < boardPositions.length; i++) {
            boardPositions[i].cambiarJugador(Manager.getJuego().getTableroDelJuego().getPosicionesDelTablero()[i].getJugadorOcupandola());
            //boardPositions[i].repaint();
        }
        repintar();
    }

    public void IniciarTablero() {

        int[][] Valid
                = {{1, 0, 0, 1, 0, 0, 1},
                {0, 1, 0, 1, 0, 1, 0},
                {0, 0, 1, 1, 1, 0, 0},
                {1, 1, 1, 0, 1, 1, 1},
                {0, 0, 1, 1, 1, 0, 0},
                {0, 1, 0, 1, 0, 1, 0},
                {1, 0, 0, 1, 0, 0, 1}};
        int x = 0;
        int y = 0;
        int pos = 0;
        boardPositions = new Panel[24];
        for (int i = 0; i < 7; i++) {
            for (int j = 0; j < 7; j++) {
                if (Valid[i][j] == 1) {
                    boardPositions[pos] = new Panel("../Images/Desocupado.jpg");
                    boardPositions[pos].setSize(60, 60);
                    boardPositions[pos].setLocation(x, y);
                    this.add(boardPositions[pos]);
                    boardPositions[pos].repaint();
                    pos++;
                    
                }
                x += 65;
            }
            x = 0;
            y += 65;
        }
        panel = new Panel("../Images/tablero.png");
        panel.setSize(500, 500);
        panel.setLocation(0, 0);

        this.add(panel);
    }

    public Agent_Manager getManager() {
        return Manager;
    }

    public void setManager(Agent_Manager Manager)  {
        this.Manager = Manager;
      //  ActualizarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(372, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(208, 208, 208))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(396, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      GuiEvent a = new GuiEvent(this, 1);
      this.Manager.Event(a);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicalBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicalBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicalBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicalBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PhysicalBoard().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
